#!/usr/bin/env bash

WIFIS="$(curl -s $NETWORK_SCANNER_ENDPOINT)"

WEATHER=$(curl -s -X GET -u $BALAAM_USER":"$BALAAM_PASSWORD --header "Accept: text/plain" --data-urlencode "wifis="$WIFIS $BALAAM_URL"/data/weather")
echo $WEATHER
