#!/usr/bin/env bash

# API Dependencies
echo "Checking Balaam API dependencies"
command -v javac > /dev/null 2>&1 
if [ $? = 0 ];
    then 
      echo "Java Compiler ... found"
    else 
      echo "Java Compiler ... NOT FOUND."
      exit 1;
fi
command -v lein > /dev/null 2>&1
if [ $? = 0 ];
    then
        echo "Leiningen ....... found"
    else
        echo "Leiningen ....... NOT FOUND"
        exit 1;
fi

exit 0 
