#!/usr/bin/env bash

set -e

# colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

printf "${GREEN}Checking balaam dependencies for $(uname) $(uname -r)${NO_COLOR}\n\n"

OPERATING_SYSTEM=$(uname)

# Docker
checkForDocker() {
    command -v docker > /dev/null 2>&1
    if [[ $? = 0 ]];
    then
        printf "Docker ... ${GREEN}FOUND${NO_COLOR}\n"
    else
        printf "Docker ... ${RED}NOT FOUND${NO_COLOR}\n"
        exit 1;
    fi
}

echo "Checking Docker"
if [[ "$OPERATING_SYSTEM" == "Linux" ]];
    then
        checkForDocker
    elif [ "$OPERATING_SYSTEM" == "Darwin" ];
    then
        command -v docker-machine > /dev/null 2>&1
        if [ $? = 0 ];
        then
            printf "Docker Machine ... ${GREEN}FOUND${NO_COLOR}\n"
        else
            printf "Docker Machine ... ${RED}NOT FOUND${NO_COLOR}\n"
            exit 1;
        fi
        checkForDocker
    else
        printf "${RED}Cannot check dependencies for unknown operating system $(uname)${NO_COLOR}\n"
        exit 1;
fi
echo ""

# API
bash ./api/scripts/check
